server:
  port: 8086
  
spring:
  application:
    name: po-producer-ms
  
kafka:
  topic: po-topic
  bootstrap-server: localhost:9092
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'